# Generated by Django 4.0.5 on 2022-06-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indie_app', '0004_concert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
