# Generated by Django 4.0.5 on 2022-06-02 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_status', models.SmallIntegerField(choices=[(0, '관객'), (1, '뮤지션')], default=0)),
                ('host_name', models.CharField(default='익명', max_length=200)),
                ('host_intro', models.TextField(null=True)),
                ('host_insta', models.CharField(max_length=200, null=True)),
                ('host_youtube', models.CharField(max_length=200, null=True)),
                ('host_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scrap', models.ManyToManyField(blank=True, related_name='scraps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
