# Generated by Django 4.0.5 on 2022-06-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_mypage_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='host',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_image',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_insta',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_intro',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_status',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='host_youtube',
        ),
        migrations.AddField(
            model_name='mypage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
