# Generated by Django 4.0.5 on 2022-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_remove_mypage_host_remove_mypage_host_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mypage',
        ),
    ]
