# Generated by Django 4.0.5 on 2022-06-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_concert_musician_name_alter_concert_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='musician_name',
        ),
    ]
