# Generated by Django 4.0.4 on 2022-06-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_name',
            field=models.CharField(default='익명', max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
