# Generated by Django 4.0.4 on 2022-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0013_feedback_feedback_name_feedback_feedback_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alarm',
            field=models.SmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=1),
        ),
    ]
