# Generated by Django 4.0.5 on 2022-06-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0014_alter_user_insta_alter_user_youtube'),
        ('account_app', '0014_user_alarm'),
    ]

    operations = [
    ]
