# Generated by Django 4.0.5 on 2022-06-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_merge_20220605_2339'),
        ('account_app', '0015_merge_20220605_2345'),
    ]

    operations = [
    ]
