# Generated by Django 3.2.13 on 2022-06-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0015_merge_20220605_2339'),
        ('account_app', '0015_merge_20220605_2354'),
    ]

    operations = [
    ]
