# Generated by Django 4.0.4 on 2022-06-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_user_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highlight',
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(default='익명', max_length=200)),
                ('highlight', models.ImageField(blank=True, null=True, upload_to='')),
                ('highlight_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
