# Generated by Django 4.0.5 on 2022-06-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0016_merge_20220606_0054'),
        ('account_app', '0016_merge_20220606_0105'),
    ]

    operations = [
    ]
