# Generated by Django 4.0.4 on 2022-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0018_remove_highlight_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='highlight_post',
        ),
        migrations.AddField(
            model_name='highlight',
            name='uploader',
            field=models.CharField(default='익명', max_length=200),
        ),
    ]
