# Generated by Django 4.0.4 on 2022-06-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0019_remove_highlight_highlight_post_highlight_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
