# Generated by Django 4.0.4 on 2022-06-05 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0020_alter_highlight_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='highlight_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
