# Generated by Django 4.0.4 on 2022-06-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0017_merge_20220606_0317'),
        ('account_app', '0021_highlight_highlight_time'),
    ]

    operations = [
    ]
